CREATE TABLE APARTMENT (
  ID INTEGER PRIMARY KEY,
  ADDRESS TEXT
);

CREATE TABLE PEOPLE (
  ID INTEGER PRIMARY KEY,
  NAME TEXT,
  AGE INTEGER,
  APARTMENT_ID INTEGER,
  FOREIGN KEY (APARTMENT_ID) REFERENCES APARTMENT(ID)
);

CREATE TABLE PET (
  ID INTEGER PRIMARY KEY,
  NAME TEXT,
  TYPE TEXT,
  APARTMENT_ID INTEGER,
  FOREIGN KEY (APARTMENT_ID) REFERENCES APARTMENT(ID)
);

INSERT INTO APARTMENT VALUES (0, 'ONE');
INSERT INTO APARTMENT VALUES (1, 'TWO');
INSERT INTO APARTMENT VALUES (2, 'THREE');
INSERT INTO APARTMENT VALUES (3, 'FOUR');
INSERT INTO APARTMENT VALUES (4, 'FIVE');


INSERT INTO PEOPLE VALUES (0, 'JACK', 30, 0);
INSERT INTO PEOPLE VALUES (1, 'SAM', 24, 0);

INSERT INTO PEOPLE VALUES (2, 'ADRIAN', 41, 1);

INSERT INTO PEOPLE VALUES (3, 'AVA', 19, 2);
INSERT INTO PEOPLE VALUES (4, 'MARK', 27, 2);


INSERT INTO PET VALUES (0, 'BUN', 'DOG', 0);
INSERT INTO PET VALUES (1, 'LUNA', 'CAT', 0);

INSERT INTO PET VALUES (2, 'MAX', 'DOG', 1);

INSERT INTO PET VALUES (3, 'NEON', 'CAT', 2);
INSERT INTO PET VALUES (4, 'ROCKY', 'DOG', 2);

INSERT INTO PET VALUES (5, 'PIP', 'BIRD', 3);
