-- create
CREATE TABLE USERS (ID INTEGER PRIMARY KEY, NAME TEXT, AGE INTEGER);
CREATE TABLE POSTS (ID INTEGER PRIMARY KEY, LIKES INTEGER DEFAULT 0, USER_ID INTEGER);
CREATE TABLE MEDIA (ID INTEGER PRIMARY KEY, POST_ID INTEGER, LINK TEXT);
CREATE TABLE LIKES (ID INTEGER PRIMARY KEY, USER_ID INTEGER, POST_ID INTEGER);

-- insert
INSERT INTO USERS VALUES (1, 'Jake', 25);
INSERT INTO USERS VALUES (2, 'Shivam', 26);
INSERT INTO USERS VALUES (3, 'Sam', 23);
INSERT INTO USERS VALUES (4, 'James', 37);
INSERT INTO USERS VALUES (5, 'Yorke', 60);


INSERT INTO POSTS (ID, USER_ID) VALUES (1, 1);
INSERT INTO POSTS (ID, USER_ID) VALUES (2, 5);
INSERT INTO POSTS (ID, USER_ID) VALUES (3, 4);
INSERT INTO POSTS (ID, USER_ID) VALUES (4, 3);
INSERT INTO POSTS (ID, USER_ID) VALUES (5, 1);
INSERT INTO POSTS (ID, USER_ID) VALUES (6, 2);


INSERT INTO MEDIA VALUES (1, 1, 'One');
INSERT INTO MEDIA VALUES (2, 2, 'Two');
INSERT INTO MEDIA VALUES (3, 3, 'Three');
INSERT INTO MEDIA VALUES (4, 4, 'Four');
INSERT INTO MEDIA VALUES (5, 5, 'Five');
INSERT INTO MEDIA VALUES (6, 6, 'Six');


INSERT INTO LIKES VALUES (1, 2, 1);
UPDATE POSTS SET LIKES = LIKES + 1 WHERE ID = 1;

INSERT INTO LIKES VALUES (2, 4, 2);
UPDATE POSTS SET LIKES = LIKES + 1 WHERE ID = 2;

INSERT INTO LIKES VALUES (3, 4, 1);
UPDATE POSTS SET LIKES = LIKES + 1 WHERE ID = 1;

INSERT INTO LIKES VALUES (4, 1, 5);
UPDATE POSTS SET LIKES = LIKES + 1 WHERE ID = 5;

INSERT INTO LIKES VALUES (5, 3, 4);
UPDATE POSTS SET LIKES = LIKES + 1 WHERE ID = 4;

INSERT INTO LIKES VALUES (6, 5, 3);
UPDATE POSTS SET LIKES = LIKES + 1 WHERE ID = 3;

-- All users and their posts with media links
SELECT USERS.NAME AS "POST BY", POSTS.ID as "POST", MEDIA.LINK
FROM POSTS
LEFT JOIN USERS ON USERS.ID = POSTS.USER_ID
LEFT JOIN MEDIA ON POSTS.ID = MEDIA.POST_ID;


-- Posts liked by users with media link and total likes
SELECT USERS.NAME AS "NAME", LIKES.POST_ID AS "LIKED POSTS", MEDIA.LINK as "LINK", POSTS.LIKES AS "TOTAL LIKES"
FROM USERS
LEFT JOIN LIKES ON USERS.ID = LIKES.USER_ID
LEFT JOIN MEDIA ON LIKES.POST_ID = MEDIA.POST_ID
LEFT JOIN POSTS ON LIKES.POST_ID = POSTS.ID;

-- List all posts and users who liked them
SELECT POSTS.ID AS "POST ID", MEDIA.LINK AS "MEDIA LINK", POSTS.LIKES AS "TOTAL LIKES", USERS.NAME AS "LIKED BY"
FROM POSTS
LEFT JOIN MEDIA ON POSTS.ID = MEDIA.POST_ID
LEFT JOIN LIKES ON POSTS.ID = LIKES.POST_ID
LEFT JOIN USERS ON LIKES.USER_ID = USERS.ID;

-- Get posts and count total likes using count and group with post id and link
SELECT POSTS.ID, COUNT(LIKES.POST_ID) AS "TOTAL LIKES", MEDIA.LINK
FROM POSTS
LEFT JOIN LIKES ON POSTS.ID = LIKES.POST_ID
LEFT JOIN MEDIA ON MEDIA.POST_ID = POSTS.ID
GROUP BY POSTS.ID, MEDIA.LINK;