CREATE TABLE PEOPLE (ID INTEGER PRIMARY KEY, NAME TEXT, AGE INTEGER, HOME_ID INTEGER);
CREATE TABLE PETS (ID INTEGER PRIMARY KEY, NAME TEXT, KIND TEXT, NEUTERED BOOLEAN, HOME_ID INTEGER);
CREATE TABLE HOME (ID INTEGER PRIMARY KEY, ADDRESS TEXT);

INSERT INTO HOME VALUES (0, 'DEO');
INSERT INTO HOME VALUES (1, 'MAN');
INSERT INTO HOME VALUES (2, 'HAR');

INSERT INTO PEOPLE VALUES (0, 'JAKE', 26, 0);
INSERT INTO PEOPLE VALUES (1, 'SAM', 23, 0);
INSERT INTO PEOPLE VALUES (2, 'ADRINO', 30, 1);
INSERT INTO PEOPLE VALUES (3, 'AV', 5, 1);
INSERT INTO PEOPLE VALUES (4, 'SAK', 19, 2);


INSERT INTO PETS VALUES (0, 'MAYA', 'DOG', FALSE, 0);
INSERT INTO PETS VALUES (1, 'JIP', 'DOG', TRUE, 1);
INSERT INTO PETS VALUES (2, 'NEON', 'CAT', TRUE, 2);


SELECT HOME.ADDRESS, PEOPLE.NAME, PETS.NAME FROM
PEOPLE
LEFT JOIN HOME ON HOME.ID = PEOPLE.HOME_ID
LEFT JOIN PETS ON HOME.ID = PETS.HOME_ID;

SELECT HOME.ADDRESS, PEOPLE.NAME FROM
PEOPLE
LEFT JOIN HOME ON PEOPLE.HOME_ID = HOME.ID
LEFT JOIN PETS ON PETS.HOME_ID = HOME.ID
WHERE PETS.NAME = 'MAYA';


SELECT H.ADDRESS FROM HOME H;