CREATE TABLE PEOPLE (ID INTEGER PRIMARY KEY, NAME TEXT, AGE INTEGER, HOME_ID INTEGER);
CREATE TABLE PETS (ID INTEGER PRIMARY KEY, NAME TEXT, KIND TEXT, NEUTERED BOOLEAN, HOME_ID INTEGER);
CREATE TABLE HOME (ID INTEGER PRIMARY KEY, ADDRESS TEXT);

INSERT INTO HOME VALUES (0, 'DEO');
INSERT INTO HOME VALUES (1, 'MAN');
INSERT INTO HOME VALUES (2, 'HAR');
INSERT INTO HOME VALUES (3, 'NEW');

INSERT INTO PEOPLE VALUES (0, 'JAKE', 26, 0);
INSERT INTO PEOPLE VALUES (1, 'SAM', 23, 0);
INSERT INTO PEOPLE VALUES (2, 'ADRINO', 30, 1);
INSERT INTO PEOPLE VALUES (3, 'AV', 5, 1);
INSERT INTO PEOPLE VALUES (4, 'SAK', 19, 2);
INSERT INTO PEOPLE VALUES (5, 'PETR', 19, 66);


INSERT INTO PETS VALUES (0, 'MAYA', 'DOG', FALSE, 0);
INSERT INTO PETS VALUES (1, 'JIP', 'DOG', TRUE, 1);
INSERT INTO PETS VALUES (2, 'NEON', 'CAT', TRUE, 2);

-- Let's jump on joins
select p.name, p.age, h.address, t.name
from people p
left join home h on h.id = p.home_id
left join pets t on t.home_id = p.home_id;